agent.sources  = apiSource
agent.channels = memChannel
agent.sinks    = fileSink

# --- SOURCE: يراقب فولدر الـ landing_zone ---
agent.sources.apiSource.type = spooldir
agent.sources.apiSource.spoolDir = /home/bigdata/Desktop/landing_zone
agent.sources.apiSource.fileSuffix = .COMPLETED
agent.sources.apiSource.deletePolicy = never
agent.sources.apiSource.ignorePattern = ^.*\.tmp$
agent.sources.apiSource.deserializer = LINE
agent.sources.apiSource.deserializer.maxLineLength = 1000000
agent.sources.apiSource.channels = memChannel

# --- CHANNEL: بافر مؤقت في الميموري ---
agent.channels.memChannel.type = memory
agent.channels.memChannel.capacity = 10000
agent.channels.memChannel.transactionCapacity = 1000

# --- SINK: يكتب الملفات في فولدر processed_zone ---
agent.sinks.fileSink.type = file_roll
agent.sinks.fileSink.channel = memChannel
agent.sinks.fileSink.sink.directory = /home/bigdata/Desktop/processed_zone
agent.sinks.fileSink.sink.rollInterval = 30
